# Jekyll configuration for Shughran Documentation
title: "Shughran Documentation"
description: "Comprehensive documentation for the Shughran organizational management system"
baseurl: "/shughran"
url: "https://rafidalhaque.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Just the Docs theme configuration
search_enabled: true
heading_anchors: true

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include/exclude files
include:
  - README.md
  - index.md

exclude:
  - vendor/
  - Gemfile*

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"